### ISSUE TITLE
lab.llvm.org HSTS for llvm.org breaks http://green.lab.llvm.org

### ISSUE THREAD

**Issue by jankratochvil** [llvm/llvm-iwg#10]
This behavior happens with both _firefox-86.0.1-1.fc33.x86_64_ and _chromium-88.0.4324.182-2.fc33.x86_64_ .
I cannot access http://green.lab.llvm.org as the browser redirects me to https://green.lab.llvm.org but this site does not support https.
It happens after accessing anything on site https://lab.llvm.org as it sets [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) for the whole _llvm.org_ domain+subdomains:
`lab.llvm.org^partitionKey=%28http%2Cllvm.org%29:HSTS    0       18706   1631821988822,1,1,2
`
One can delete the line in `~/.mozilla/**/SiteSecurityServiceState.txt` but soon it gets added again from accessing any buildbot on lab.llvm.org .
Sure another/better solution would be to fix _green.lab.llvm.org_ to support https.

**Comment by ChristianKuehnel** [comment]
@asl can you please take a look at this? I guess you are familiar with the domains. Maybe we should forward this to the person running the Green Dragons...

**Comment by asl** [comment]
I don't think we should do anything wrt this as green dragon is simply down and as far as I know won't be restored. Though, lab.llvm.org HSTS should be fixed. Tagging @andreil99

**Comment by jankratochvil** [comment]
http://green.lab.llvm.org/green/ is perfectly alive, last build is "Mar 22, 2021 11:32:57 AM":
http://green.lab.llvm.org/green/job/clang-stage1-RA/19584/

**Comment by gkistanova** [comment]
Thanks for reporting, @ChristianKuehnel!

The change was not intentional in the first place.

This is fixed now.
HSTS is set for lab.llvm.org only and does not affect any other llvm.org domains.

Affected users would need to clean the cached settings, though.

**Comment by jankratochvil** [comment]
FYI I get also HSTS for llvm.org from http://reviews.llvm.org:
`reviews.llvm.org^partitionKey=%28http%2Cllvm.org%29:HSTS        0       18708   1679513348619,1,1,2
`
But surprisingly it does not affect accessing http://green.lab.llvm.org for me.

**Comment by azharudd** [comment]
> I don't think we should do anything wrt this as green dragon is simply down and as far as I know won't be restored.

@asl, Green Dragon is supposed to be, and is, perfectly up and and running. :)

**Comment by azharudd** [comment]
I've also added `https` support to Green Dragon (https://green.lab.llvm.org/green/). @jankratochvil, can you please try that url now.

**Comment by jankratochvil** [comment]
@azharudd Yes, https://green.lab.llvm.org does work now (as long as the Let's Encrypt cert will keep to be refreshed), thanks.
So now the HSTS for llvm.org is no longer an issue. Maybe green.lab.llvm.org could set HSTS for green.lab.llvm.org and/or other sites could set it back for whole llvm.org (if there isn't some other http-only site) etc.
