### ISSUE TITLE
Discourse feature request: subscribing to categories transitively

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#101]
from meeting on 2022-03-01:
It would be good to have a "transitive category watch" feature in Discourse: 
If you watch the top level category, you're also watching all sub-categories below that. 
Otherwise users need to manually select every sub-category and are missing new sub-categories.

@tlattner can you please raise this as a feature request with Discourse?

**Comment by keith** [comment]
I'm not sure if this is being discussed elsewhere but I think re-enabling mailing list mode would help with the issues mentioned in the meeting notes, I imagine most folks would enable that and then work back their subscriptions to specific categories as posts came in that they weren't interested in tracking.

**Comment by tlattner** [comment]
> I'm not sure if this is being discussed elsewhere but I think re-enabling mailing list mode would help with the issues mentioned in the meeting notes, I imagine most folks would enable that and then work back their subscriptions to specific categories as posts came in that they weren't interested in tracking.

Mailing list mode has been re-enabled for a few weeks now.

**Comment by keith** [comment]
Oh awesome, thanks!

**Comment by keith** [comment]
Oh awesome, thanks!
