### ISSUE TITLE
Migrate phabricator to foundation owned infrastructure

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#110]
This is a follow up to #87:
Migrate all of Phabricator on Google Cloud from a Google-internal project to the project owned by the LLVM foundation.

@joker-eph can you please lead this one?

**Comment by joker-eph** [comment]
Considering the set-date to migrate to GitHub in ~1y from now, I'm not sure it is a good use of time to invest in Phabricator right now...

**Comment by ChristianKuehnel** [comment]
@joker-eph oh I missed that. Where did you see this announcement?
So you don't want to migrate Phbricator to the foundation-owned Google Cloud project any more?

**Comment by ChristianKuehnel** [comment]
Ah found the link: https://discourse.llvm.org/t/code-review-process-update/63964

**Comment by tlattner** [comment]
I still would really like all the porn accounts removed from Phabricator. Maybe that doesn't require moving to a location that others can access the internals, but it would be good to know exactly how to make this happen.  It would also be good to sort out the chain of command on who to contact when we have immediate issues with content or something else on the site. 

I also assume once we move to GitHub PRs, people are going to want to maintain all of the history in Phab forever and have the links work.

**Comment by joker-eph** [comment]
> I still would really like all the porn accounts removed from Phabricator.

It is just a matter of someone providing the list of accounts: the actual removal is trivial. Note that right now we only allow GitHub account so they are likely connecting through GitHub.

>  It would also be good to sort out the chain of command on who to contact when we have immediate issues with content or something else on the site.

Maskray (US), Ben Kramer (EMEA), or myself all have direct access to the VM hosting Phab right now.

**Comment by tlattner** [comment]
Do you just need the username? What format do you want it in?

I downloaded all the users and there are around 19,000.

**Comment by tlattner** [comment]
> > I still would really like all the porn accounts removed from Phabricator.
> 
> It is just a matter of someone providing the list of accounts: the actual removal is trivial. Note that right now we only allow GitHub account so they are likely connecting through GitHub.
> 
> > It would also be good to sort out the chain of command on who to contact when we have immediate issues with content or something else on the site.
> 
> Maskray (US), Ben Kramer (EMEA), or myself all have direct access to the VM hosting Phab right now.

I don't think I have all these emails. Can you share them with me? Thanks!

**Comment by joker-eph** [comment]
> Do you just need the username? What format do you want it in?

Yes, just the username, any format that I can script is fine, the easiest is one username per line in a text file.

> > Maskray (US), Ben Kramer (EMEA), or myself all have direct access to the VM hosting Phab right now.
> I don't think I have all these emails. Can you share them with me? Thanks!

Will followup by email.

**Comment by ChristianKuehnel** [comment]
Closing (for now) as LLVM will migrate to Pull Requests, so a migration of Phabricator doesn't make sense at the moment. Please re-open if anything changes.
