### ISSUE TITLE
Set up Kanban board for our working group

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#15]
We want to have a Kanban board for our working group so we can track the topics we're currently working on, similar to Christian's project: https://github.com/ChristianKuehnel/iwg-workspace/projects/1

At the moment the "projects" feature of GitHub is disabled for all LLVM projects. We probably need to talk to the admins to be able to use that.

**Comment by asl** [comment]
Projects are enabled

**Comment by lazyparser** [comment]
> Projects are enabled

Thanks @asl :)

**Comment by ChristianKuehnel** [comment]
Awesome, thx!
I create a Kanban board for us: https://github.com/llvm/llvm-iwg/projects/1

Please let me know if you want anything changes. Also happy to give other people admin access for this...
