### ISSUE TITLE
Document generation of the website

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#17]
I did not find any documentation on how to generate the html code of the website from the monorepo. This would be useful to have to test changes locally.

Once we have that, add this to the documentation tutorials so people find it:
* https://llvm.org/docs/MarkdownQuickstartTemplate.html
* https://llvm.org/docs/SphinxQuickstartTemplate.html

**Comment by ChristianKuehnel** [comment]
some discussion on the mailing list recently, check that for details

**Comment by ChristianKuehnel** [comment]
Dug up the commands as I just tested my own documentation change, maybe that helps:

``` bash
# tools needed in addition to cmake, ninja, build-essentials, ...
sudo apt install -y sphinx-doc python-recommonmark-doc
mkdir build
cd build
cmake -G Ninja -DLLVM_ENABLE_SPHINX=On ../llvm
ninja docs-llvm-html
```

**Comment by tstellar** [comment]
I wrote a script here: https://reviews.llvm.org/D95284

**Comment by ChristianKuehnel** [comment]
I added a pure documentation patch for manually creating the documentation locally:
https://reviews.llvm.org/D107460
