### ISSUE TITLE
Mac-Hardware for pre-merge testing

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#32]
Louis Dionne requested Mac-Hardware for pre-merge testing, details see email conversation on iwg@llvm.org

**Comment by sqlbyme** [comment]
I have spoken with Louis in the past about this and I know he could really use our support here.  @ChristianKuehnel would it be possible for you to get a quote from MacStadium?  I will work up pricing information for AWS.  It would be nice if we could get a third vendor for price comparison.  I am going to aim to get my information posted here by the end of this week.  In order to help Louis I think it would be nice if we could get an email proposal sent to the Board within the next 10 - 14 business days.  Any objections?

**Comment by sqlbyme** [comment]
A quick peak [here](https://aws.amazon.com/ec2/instance-types/mac/) shows AWS provides macOS on dedicated hardware only.  We could get 12 cores with 32GB ram for ~$615/mo with a 1yr commitment.  The price increases dramatically if we just pay for the unit hourly (almost $2/hr).

**Comment by ChristianKuehnel** [comment]
Hi Mike,

I'll work with Louis on picking some reasonable hardware and then try to
get a quote for it.

Best,
Christian

**Comment by ChristianKuehnel** [comment]
I found two more pages with price information, looks similar to MacStadium
https://www.macminivault.com/dedicated-sign-up/
https://www.macincloud.com/pages/dedicated.html

**Comment by ChristianKuehnel** [comment]
Concerning hardware selection:
* The more cores the better for compiling (as always). So I would *not* take any dual-core machines.
* We probably want a mix of Intel (current fleet) and M1 machines (future architecture).

**Comment by ChristianKuehnel** [comment]
pre-mege testing is running on Buildkite:
https://buildkite.com/llvm-project

**Comment by ChristianKuehnel** [comment]
I created a [proposal in a Google Doc](https://docs.google.com/document/d/1gGPIvsUd7hLIRK8Kq3h_otlnpImBgBZlHSONvLWMe1E/). Not sharing it publicly as it contains pricing information:


Happy to give access to folks who want to get involved in the topic.

**Comment by tstellar** [comment]
Hi, there is a board meeting on Friday.  Is this document ready for the board to review?

**Comment by ChristianKuehnel** [comment]
Hi Tom,

from my point of view yes, but also I'm biased towards improving pre-merge
testing.
We only heard feedback from one other person on the IWG so far.

Best,
Christian

**Comment by tstellar** [comment]
I agree with the MacMiniVault choice.  Do you want to send the proposal to the board?

**Comment by ChristianKuehnel** [comment]
Well, the formal question is: Do we want more people from the IWG to
review/approve this proposal?

So far we don't really have agreed if/how we want to decide such things...

Best,
Christian

**Comment by sqlbyme** [comment]
I'd like the IWG to have a chance to meet once and discuss this live before
we present to the Board.  Tom, I think we should just let the Board know a
proposal will be provided soon via email.  We can ask the Board to approve
via email, we should not have to wait until the June meeting to get this
approved.

-Mike

**Comment by tstellar** [comment]
@sqlbyme Ok, that makes sense.

**Comment by lazyparser** [comment]
Hi,

is this request still relevant? I've just set up 2 mac mini M1 and 1 mac mini x86 i5 (2012) for building LLVM and Spidermonkey. Still working on environment setting, but I'd like to contribute them to the LLVM test process.

**Comment by tstellar** [comment]
@lazyparser We have purchased the Mac resources and they are running in buildkite.  If you have resources you want to contribute, please open a separate ticket so we can discuss.

**Comment by lazyparser** [comment]
> @lazyparser We have purchased the Mac resources and they are running in buildkite. If you have resources you want to contribute, please open a separate ticket so we can discuss.

Got it. Thanks. will do later.

**Comment by ChristianKuehnel** [comment]
Also feel free to sync up with Louis Dionne on setting things up.

**Comment by ChristianKuehnel** [comment]
Clsoing as the hardware is up and running
