### ISSUE TITLE
[Discourse migration] Can we preserve the links to the email archive?

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#46]
People frequently refer to emails via their archive links. Also people link emails to other emails via the archive URLs. So it would be really important to find a way to preserve the links after the migration.

It would be great if archive links between emails would be upgraded to links within Discourse. So that clicking on such a link it gets opened in Discourse, not the mailing list archive.

**Comment by ChristianKuehnel** [comment]
@sqlbyme since you were talking to Discourse (the company): Can you please raise the question there?

**Comment by ChristianKuehnel** [comment]
@sqlbyme any news on this topic?

**Comment by ChristianKuehnel** [comment]
@tlattner please discuss this with the folks from Discourse.

**Comment by ChristianKuehnel** [comment]
Hi @tlattner ,
Have you found a solution for this? Or do we need someone to investigate the options further?
In any case we should be transparent about this in the documentation.

**Comment by tlattner** [comment]
We do not plan to support any redirect. The old archives will exist for reference on the web server for any old links.

**Comment by tlattner** [comment]
Keep in mind that any post can be edited by an admin at any point. So if someone really wants to fix up a link, we can do it (f they can't).

**Comment by ChristianKuehnel** [comment]
OK, I'll propose an extension to the documentation.

I was mostly concerned with links in commits and code reviews. People
sometimes refer to a discussion on the mailing list via link as background
to a certain decision/design in the code
,.

Best,
Christian

**Comment by ChristianKuehnel** [comment]
The string `lists.llvm.org/pipermail/`occurs around times in the sources of llvm-project. I suppose these should be updated to point to Discourse after the migration and before we shut down the mailing list archive...
