### ISSUE TITLE
Mailman - investigate short termin solutions

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#5]
owners: Mishal, Philip, Anton
goals: 
* identify 1-2 reasonable companies, 
* contact them, 
* understand if they can solve our problems, 
* understand pricing for our use case,
* understand if this is a feasible solution

**Comment by ChristianKuehnel** [comment]
Meeting on 2021-03-30:
no updates, Christian will reach out to get a status

**Comment by asl** [comment]
As far as I heard from Tanya, captcha was installed. This reduced the amount of spam logins, the situation is being monitored.
