### ISSUE TITLE
Bugzilla to GitHub issues migration

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#56]
Just for tracking the infrastructure effort, the IWG is not involved in this activity.

Current issue tracker: https://bugs.llvm.org/
Original RFC: https://lists.llvm.org/pipermail/llvm-dev/2020-July/143274.html
Request for mapping user names: https://lists.llvm.org/pipermail/llvm-dev/2021-March/149441.html

**Comment by ChristianKuehnel** [comment]
from the meeting:
* [status doc](https://bit.ly/3HVjr7a)
* depending on GitHub engineers for final step of migration as we need to use an internal API
  * last week were stuck on some bugs, that were fixed by GitHub
  * also delayed because of GitHub outage
  * another attempt on Friday revealed another bug (handling of circular links between issues). Probably affecting 5000 issues.
  * so far 13k issues were imported, 1k affected by the bug
  * example issue with the bug: https://github.com/llvm/llvm-project/issues/1146 where the link is missing
     > *** Bug llvm/llvm-bugzilla-archive#8125 has been marked as a duplicate of this bug. ***
* migration stuck at the moment, discussion on alternatives, waiting for GitHub engineers
* We can move issues between projects, via the API
  * however this triggers notifications to all users (3.5k users x 50k issues)
  * this would also update the last-modified date
* The tooling to export the bugs from Bugzilla is in https://github.com/llvm/bugzilla2gitlab/tree/llvm

**Conclusion form the meeting:**
* Wait for 48h to see if GitHub can resolve the issue.
* Even if we can't resolve the circular dependencies: We should migrate anyway as we can live with that defect.
* We should express our support in the mailing list, Christian to draft a statement.

**Comment by ljmf00** [comment]
@asl since https://github.com/llvm/llvm-project/issues/52603 got closed and the issue mention "Closes #56" I thought about pinging you.

Also, is there any updated version of https://github.com/llvm/bugzilla2gitlab/tree/llvm ? Other big projects that use Bugzilla and want to proceed with a migration might get interested and have some base to work with :)

**Comment by asl** [comment]
@ljmf00 This is the final version. Why do you ask?

**Comment by ljmf00** [comment]
> @ljmf00 This is the final version. Why do you ask?

Thanks for clarifying. D programming language is in the same situation and wants to move forward with a migration, hence my question. I mentioned you on the D mailing list about your work and thought it was somehow outdated due to mentioning Gitlab instead of Github.

**Comment by asl** [comment]
No it's correct. Long story short: you cannot migrate to GitHub without GitHub help (e.g. you cannot impersonate other users or silence notifications). One way to do so – import everything to GitLab (and verify the results) and then use GitHub Enterprise tools for GitLab => GitHub migration.

I will be happy to describe our bumps and humps over the call, if you'd like :)

**Comment by ljmf00** [comment]
> No it's correct. Long story short: you cannot migrate to GitHub without GitHub help (e.g. you cannot impersonate other users or silence notifications). One way to do so – import everything to GitLab (and verify the results) and then use GitHub Enterprise tools for GitLab => GitHub migration.
> 
> I will be happy to describe our bumps and humps over the call, if you'd like :)

I'm not involved in the migration process, but thanks for the information and your availability to help. However, I think whoever is involved in that process would appreciate that. [Here](https://forum.dlang.org/thread/wnnwxyjtizvhyswwqehz@forum.dlang.org)'s the thread, in case you are interested and find something worth noting in that regard :)
