### ISSUE TITLE
Discourse - how to merge my account with an "staged user" acount?

### ISSUE THREAD

**Issue by banach-space** [llvm/llvm-iwg#91]
Hello,

Thanks very much for all the effort migrating the mailing lists to Discourse!

I've just had a quick a look and noticed that a new "staged user" was created for my posts to the mailing lists (I used to use my work e-mail for posting to llvm-dev). That's different to my regular Discourse account that I have been using for a while now (I used my personal e-mail to open it). How can I merge the two accounts together? I've tried adding a secondary e-mail to my Discourse account, but it's not possible. I assume that it is assigned to the "staged user" account created during the migration.

Thank you,
-Andrzej

**Comment by ChristianKuehnel** [comment]
@tlattner can you please forward that question to Discourse?

**Comment by banach-space** [comment]
I've just noticed [[Post Discourse Migration Information](https://discourse.llvm.org/t/post-discourse-migration-information/59719)](https://discourse.llvm.org/t/post-discourse-migration-information/59719). Let me close this ticket and I will e-mail discourse-admin@llvm.org instead. This way all requests will be in one place.

Thanks,
-Andrzej
