### ISSUE TITLE
Address additional feedback on Discourse migration

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-iwg#98]
I think there's some feedback worth discussing on the Discourse migration thread:
https://discourse.llvm.org/t/retrospective-the-move-to-discourse-feedback-by-march-7th/59861/13?u=rnk

I'm filing this issue so we can discuss it at the next IWG meeting. Aaron's final sentence seems like a good take away:
"Relatedly, I think the community needs a transparent way to judge community consensus before any further infrastructure projects are undertaken."

We've discussed the importance of transparency before and proposed some ideas for achieving it, but I don't feel like we are following through on our commitments or making progress yet. Aaron clearly considers this a blocking issue before we undertake additional infrastructure improvements.

**Comment by ChristianKuehnel** [comment]
My gut feeling on this is that we should have a multi-step process for larger infrastructure changes:

1. Someone raises the topic and the IWG tries to get a basic understanding of the problem and potential solutions. 
2. The IWG asks for qualitative input and then summarizes that (as with PullRequests).
3. The IWG runs a survey with the community to also get quantitative input: How many people are impacted by the problem? Which is the prefered solution? How many people are impacted by a potential show-stopper?
4. The IWG proposes the change (in writing, with pointers to the data) to the board who then takes the decision

All of that data should be made public.

**Comment by ChristianKuehnel** [comment]
from meeting on 2022-03-01:
* How do we involve the community in such decisions?
  * Do more polls on Discourse (in an announce category)?
* process proposal:
  * discuss topic on Discourse / IWG / some other community tool
  * once the proposal is clear enough: run poll on Discourse to get initial feedback
  * if feedback is positive then figure out the details 
  * do a 2nd poll for a final sign-off
* candidates to try this process:
  * discuss direction for pre-merge testing, options:
    * it's good, keep it, make it better
    * turn it down, it's a waste of time

**Comment by rnk** [comment]
I agree, gathering input and making decisions is a long process, but I think the final decision for these migrations needs signoff from the community. In the IWG meeting, I proposed the idea of sending a poll to the LLVM announce list and creating up-or-down polls for "large" infra changes. This represents signoff, and the options are sort of "yes, we are ready for this change", or "no, it still needs work and has unaddressed concerns".

**Comment by joker-eph** [comment]
> do a 2nd poll for a final sign-off

Why would polling be introduced as a decision process now? What happened to the RFC process?

**Comment by rnk** [comment]
I am not proposing replacing the RFC process for technical LLVM changes, I am proposing a process change for future large-scale infrastructure changes.

I take "RFC" literally: it stands for request for comments. It is asking for free text responses or opinions on some proposal. It helps gather input. Our existing practices lack finality, though. They are "silence based". There's no point at which discussion concludes. So, if we take the Mailman -> Discourse migration, it was proposed as an RFC, concerns were raised, time passed, then the migration was implemented, and people felt like their concerns hadn't been addressed. I think a yes/no poll would have shown a fair amount of hesitancy in the community, and those concerns could have been addressed.

**Comment by joker-eph** [comment]
You seem to take « RFC » in a casual sense here, but there is a formal process!

One of the feedback about the Discourse migration is that it didn’t follow the process!

> This transition did not follow the usual RFC process by the community nor the one that was proposed by Chris in https://github.com/llvm/llvm-www/blob/main/proposals/LP0001-LLVMDecisionMaking.md
